proxies:
  - name: Ikada
    server: ruangguru.com
    port: 443
    type: vmess
    uuid: 2a9c6e86-a746-4829-9398-3b66222b1e7a
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /buy-vmess-ws-pm-telegram-at-synricha
      headers:
        Host: ikada.sing-box.id
    udp: true
